---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop
  labels:
    name: workshop
    environment: development
    app.kubernetes.io/name: workshop
    app.kubernetes.io/component: infrastructure
