name: Workshop API Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    

    - name: Run tests and generate Allure report
      run: |
        mvn clean test -Dmaven.test.failure.ignore=true
        mvn io.qameta.allure:allure-maven:report
    
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/allure-report
        retention-days: 30

    - name: Upload TestNG Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testng-report
        path: target/surefire-reports
        retention-days: 30