name: Workshop API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Create Allure results directory
      run: mkdir -p target/allure-results
      
    - name: Run tests with Allure
      run: |
        mvn clean test -Dmaven.test.failure.ignore=true site io.qameta.allure:allure-maven:serve
    
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: target/allure-results
        retention-days: 30


    - name: Generate Allure Report
      if: always()
      run: |
        allure generate target/allure-results --clean -o target/allure-report
        allure serve target/allure-results

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/allure-report
        retention-days: 30
