name: Workshop API Tests with Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Run tests with Allure
      run: |
        mvn clean test -Dmaven.test.failure.ignore=true
        mvn io.qameta.allure:allure-maven:serve -Dallure.maven.allureDownloadUrl=https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.1/allure-commandline-2.29.1.zip
      env:
        ALLURE_RESULTS_DIR: target/allure-results
    
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: target/allure-results
        retention-days: 30
    
    - name: Generate Allure Report
      if: always()
      run: |
        mvn io.qameta.allure:allure-maven:report -Dallure.maven.allureDownloadUrl=https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.1/allure-commandline-2.29.1.zip
    
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven-plugin
        retention-days: 30
